plugin: aws_ec2
regions:
  - "us-east-1"
filters:
  #tag:stack-name: k8s-prj
  tag:Name: Kube Master 1st on Ubuntu 20.04 of k8s-prj
hostnames:
  - "private-ip-address"
compose:
  ansible_user: "'ubuntu'"